### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by RlonRyan** [MountainBuffalo/Cacher#10]
Currently Cacher has no CI working for it. This is unacceptable. I would suggest Travis-CI, which is free for open-source projects, and rather easy to use. However, an official decision should be made as to what provider should be used and how it should act. Thus, this issue was created.

**Comment by jay18001** [comment]
Travis is fine, but we need unit test for it to really matter.

**Comment by jay18001** [comment]
Done
