### ISSUE TITLE
Cache Levels

### ISSUE THREAD

**Issue by RlonRyan** [MountainBuffalo/Cacher#3]
Caches often have several different choices for storage levels, with the three most common being:

1. Memory Only
2. Memory & Disk
3. Disk Only

Given that these are the most common options, Cacher should support them.

**Comment by jay18001** [comment]
We already support 1 and 2. I don't see 3 as that important.

**Comment by RlonRyan** [comment]
Three would be important in the event that we are caching large files, that should only be loaded into main memory when absolutely necessary.
