### ISSUE TITLE
Expiration Policy

### ISSUE THREAD

**Issue by RlonRyan** [MountainBuffalo/Cacher#4]
Typically, one caches elements that have finite lifespans, given that if they had infinite lifespans they would just be compiled into the application. Thus, Cacher needs to support some method of expiration for elements in a cache, preferably as defined by some extensible policy object.

**Comment by RlonRyan** [comment]
The following document might serve as a template for the design and implementation of this: https://github.com/google/guava/wiki/CachesExplained.

**Comment by jay18001** [comment]
Fixed in #25
