### ISSUE TITLE
Cache Path Should Be Final

### ISSUE THREAD

**Issue by RlonRyan** [MountainBuffalo/Cacher#6]
Leaving the cache path mutable does not make sense, given that if the cache path is changed at some point, all prior cached files are lost from tracking. Furthermore, caches are rarely moved, to the point that it would likely be more appropriate to instead have a copy constructor for use in moving the cache.

**Comment by jay18001** [comment]
I like having the ability to change the default caching location if the user wants. If they don't want to change it then they don't have to.

**Comment by RlonRyan** [comment]
The user should be able to set the cache location at the time of the cache's construction, but not be able to modify it after that point in time, since moving the cache would be a costly operation that should not be undertaken lightly, that would involve copying and creating a new cache anyways. Thus, we should make it so caches cannot be moved, but can be copied into new locations.

**Comment by jay18001** [comment]
We're not going to move it. That's up to the caller. Also moving files on iOS is very fast.

**Comment by RlonRyan** [comment]
Well with the current implementation can't I load a cache with elements, set the path to something new, and then suddenly all the elements that were in the cache are suddenly missing from the storage location?
