### ISSUE TITLE
Caches Have No Size Option

### ISSUE THREAD

**Issue by RlonRyan** [MountainBuffalo/Cacher#7]
Often caches are limited by size, so that the cache does not take over the entire memory of the device. As such, Cacher caches should have an option as to set a maximum size.

Arguably, for simplicity's sake, all caches should be required to have a constant maximum size, so that array allocations do not have to be done over and over.

**Comment by jay18001** [comment]
NSCache handles that under the hood and calls the delegate when It's about to delete something give us a chance to save it to disk when its of type `.disk`

**Comment by RlonRyan** [comment]
When I say size, I mean the maximum number of elements allowed in the cache, which is not necessarily correlated to the actual memory footprint of all the elements in the cache, but would serve as to determine when an addition would cause an eviction due to element count.

**Comment by jay18001** [comment]
That's not needed.

**Comment by RlonRyan** [comment]
Then we'd be limited to only one eviction policies based on the time of the element's addition to the cache.

**Comment by jay18001** [comment]
No, It's automatically handled by the system, when the user is running low on memory the system sends a notification, they is caught by NSCache and items are removed to free up system resources.

**Comment by RlonRyan** [comment]
Yeah, but what if we don't want to grow the cache until the system runs out of memory. What if we only want to keep say, the last *n* responses from the server in the cache?
