### ISSUE TITLE
Caches Should Support Custom Resource Acquirers

### ISSUE THREAD

**Issue by RlonRyan** [MountainBuffalo/Cacher#9]
Instead of always using the built-in downloader, caches should be able to be constructed with a custom resource acquirer conforming to a CacheResourceAcquirer protocol.

**Comment by jay18001** [comment]
The user will almost always use `NSURLSession`. The only other time is if they use `Alamofire` which uses NSURLSession under the hood.

**Comment by RlonRyan** [comment]
Well, if you allow for custom acquirers, then you could implement one where you don't have to type the full path of the resource to be acquired, instead the acquirer would determine it for you. It would mean fewer keystrokes for developers.

**Comment by jay18001** [comment]
Either way you have to give the full URL to the system one way or another

**Comment by RlonRyan** [comment]
Well in the first way you have to give a full URL every time, that is properly formatted, in the second way you only have to add some code that constructs the full, properly-formatted URL from the part of the URL that is of interest. In that manner for most of the requests you cut down on how much you are actually typing.

**Comment by jay18001** [comment]
Thats should be done in the users implementation

**Comment by RlonRyan** [comment]
And the protocol would allow that.
